### ISSUE TITLE
flag provided but not defined

### ISSUE THREAD

**Issue by XuChen-14** [zmap/zdns#91] opened 2017-03-10 10:32 UTC
I performed this command:  cat ./top-1m.csv | ./zdns MX --lookup-ipv4 --alexa , and  the answer was ”flag provided but not defined: -lookup-ipv4”.Does it need other module?

**Comment by zakird** [comment] 2017-03-10 11:50
This looks to be a duplicate of #88.

**Closed as completed by zakird** 2017-03-10 11:50 UTC
Labels: duplicate
