### ISSUE TITLE
zdns fails to handle message truncation in iterative mode

### ISSUE THREAD

**Issue by yairhoff** [zmap/zdns#255] opened 2021-10-19 08:17 UTC
When I run the following command:
echo ecer.com | ./zdns TXT --iterative -retries 2

I get the following answer:
{"data":{"protocol":"udp","resolver":"106.11.41.154:53"},"error":"dns: overflowing header size","name":"ecer.com","status":"ERROR","timestamp":"2021-10-19T10:24:43+03:00"}

it seems that the above error occurs when unpacking the message header, but the "truncated" bit isn't set

**Comment by phillip-stephens** [comment] 2024-07-15 16:35
Hey @yairhoff! Apologies it's taken so long to get to this.

I'm unable to reproduce with the latest ZDNS:
```
echo ecer.com | ./zdns TXT --iterative --retries 2
{"data":{"answers":[{"answer":"google-site-verification=iknQgEWUUIgJwPuzk6L0SdNH3UziywAKjQ9tbGT6ORw","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=gdvuNiax729lxbSICQ7LPUXpxOSqhRFoTSMWB8DKf3M","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=bBK2cxgPSCSp6cXPqjMo1PwWdsv_8naL4gzQ_9nsKk4","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=_HfuA5oM_vAEjwTfHf0e_vkrBgMGItN7LtGVYSST3Vc","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=SmuiNMXWgz6DWfmfEepcPOfSI6ECAhsTWTbBoBnGerc","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=RT73FPuC5jLCLXpQruhKlzzU9bjPYFhWjJlvmLO1jgU","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=LKoTOf9LcEgOrmG3vBbaTHRdCflBl1D8xNGI9R2Cb9U","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=ATLiAZvir7IVFj_Zm1I8R4M58JQVJCr8wWrcZz6CjdQ","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=-1T4RfTfT3-sGXb80Vm6KLwLnNxJlWYCYl-XinfsDg4","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"facebook-domain-verification=huo9e8uminqlkh6vo0juta0haz47y6","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"facebook-domain-verification=efsp7robvd9me566bk9zjjrj41bl9f","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"ww4x888qrhsk5fth42sy13xhmrlh2qpc","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"v=spf1 ip4:119.254.28.224/27 ip4:119.254.30.192/26 ip4:119.254.80.64/28 ip4:119.254.28.48/28 -all","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"},{"answer":"google-site-verification=tNUzlTjcWk4fPFh1aJD7Pd_MmksQwZkD2XALondC5gQ","class":"IN","name":"ecer.com","ttl":600,"type":"TXT"}],"protocol":"udp","resolver":"121.40.6.163:53"},"name":"ecer.com","status":"NOERROR","timestamp":"2024-07-15T12:20:18-04:00"}
```

This looks reasonable to me. @zakird unless you see something I'm missing, I'll close this. @yairhoff or anyone else who runs into this again, feel free to re-open with more information on how to reproduce.

**Closed as completed by phillip-stephens** 2024-07-15 16:35 UTC
Labels: bug
