### ISSUE TITLE
alookup module improperly handles domain capitalization

### ISSUE THREAD

**Issue by sumanthvrao** [zmap/zdns#324] opened 2023-02-22 00:01 UTC
Looks like `alookup` fails to return data for capitalized domains

```
-> echo ucsd.edu | zdns alookup                  
{"data":{"ipv4_addresses":["75.2.44.127","99.83.137.54"]},"name":"ucsd.edu","status":"NOERROR","timestamp":"2023-02-21T15:51:54-08:00"}

-> echo UCSD.edu | zdns alookup
{"data":{},"name":"UCSD.edu","status":"NOERROR","timestamp":"2023-02-21T15:52:01-08:00"}

```

This isn't the case for nslookup (`echo UCSD.edu | zdns nslookup` works just fine)

**Comment by phillip-stephens** [comment] 2024-06-12 05:03
Not sure what version of the code you're using, but on the latest `main`, I'm not seeing this bug.
```
~/zdns/zdns-working on  main! ⌚ 13:58:38
$ echo ucsd.edu | ./zdns alookup
{"data":{"ipv4_addresses":["99.83.137.54","75.2.44.127"]},"name":"ucsd.edu","status":"NOERROR","timestamp":"2024-06-12T13:58:42+09:00"}

~/zdns/zdns-working on  main! ⌚ 13:58:42
$ echo UCSD.edu | ./zdns alookup
{"data":{"ipv4_addresses":["75.2.44.127","99.83.137.54"]},"name":"UCSD.edu","status":"NOERROR","timestamp":"2024-06-12T13:58:45+09:00"}

```

Doesn't look to be a problem in tagged version `v1.1.0` either:
```
~/zdns/zdns-working on  main! ⌚ 13:58:38
$ echo ucsd.edu | ./zdns alookup
{"data":{"ipv4_addresses":["99.83.137.54","75.2.44.127"]},"name":"ucsd.edu","status":"NOERROR","timestamp":"2024-06-12T13:58:42+09:00"}

~/zdns/zdns-working on  main! ⌚ 13:58:42
$ echo UCSD.edu | ./zdns alookup
{"data":{"ipv4_addresses":["75.2.44.127","99.83.137.54"]},"name":"UCSD.edu","status":"NOERROR","timestamp":"2024-06-12T13:58:45+09:00"}

```

I'm going to close this since I can't reproduce, if anyone sees this behavior again please re-open, provide your version used and a reproducible example, and I'll triage then!

**Closed as completed by phillip-stephens** 2024-06-12 05:03 UTC
Labels: bug
