### ISSUE TITLE
Excess FD errors

### ISSUE THREAD

**Issue by chris-wood** [zmap/zdns#250] opened 2021-09-06 15:06 UTC
Running from a fresh build of tip of `master` on macOS, I'm seeing the following:

```
$ echo "google.com" | ./zdns A
{"data":{"protocol":"udp","resolver":"[2001:558:feed::2]:53"},"error":"write udp 10.0.0.184:59008-\u003e[2001:558:feed::2]:53: address 2001:558:feed::2: non-IPv4 address","name":"google.com","status":"ERROR","timestamp":"2021-09-05T20:38:25-07:00"}
FATA[0000] unable to create socketlisten udp 10.0.0.184:0: socket: too many open files 
```

I assume this isn't expected, so I'm wondering if this is a regression. I could of course be using it wrong, too! Happy to provide any additional information if it would be helpful.

**Comment by zakird** [comment] 2021-09-06 15:18
I don't think this is a regression. ZDNS does preemptively open thr FDs at
the start now. You either need to decrease the number of workers or
increase the number of the FDs you can open.

**Comment by chris-wood** [comment] 2021-09-06 19:29
Capping the number of worker threads did the trick. Maybe bumping the default down to something smaller would be useful? The fix wasn't obvious to me 🤷  If not, we can close.

**Comment by zakird** [comment] 2023-11-04 08:31
At the very least we should output a useful error so that the user knows what's going on and how to fix

**Comment by zakird** [comment] 2024-11-04 21:08
I'm going to close this since #448 was merged, which should prevent this problem in most all cases. If folks want to manually up the rates, they can.

**Closed as completed by zakird** 2024-11-04 21:08 UTC
